targets:
  $default:
    builders:
      json_serializable:
        generate_for:
          - lib/models/**.dart
      source_gen:combining_builder:
        generate_for:
          - lib/models/**.dart
      jaspr_builder:apps:
        generate_for:
          - lib/*.dart
