name: cv_app_base
description: A classic web app using separate html, css and dart files with ssr & manual client hydration.
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  collection: ^1.17.1
  freezed_annotation: ^2.2.0
  jaspr: ^0.9.3
  jaspr_riverpod: ^0.3.8
  json_annotation: ^4.8.0

dependency_overrides:

dev_dependencies:
  build_runner: ^2.4.0
  build_web_compilers: ^4.0.4
  lints: ^3.0.0
  freezed: ^2.3.2
  json_serializable: ^6.6.1

jaspr:
  uses-ssr: false
