name: cv_app_base
description: A classic web app using separate html, css and dart files with ssr & manual client hydration.
version: 2.1.0

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  collection: ^1.17.1
  freezed_annotation: ^2.2.0
  jaspr: ^0.9.0
  jaspr_riverpod: ^0.3.6
  js: ^0.6.5
  json_annotation: ^4.8.1

dependency_overrides:
  # riverpod: 2.1.3

dev_dependencies:
  freezed: ^2.3.2
  json_serializable: ^6.7.1
  build_runner: ^2.4.0
  build_web_compilers: ^4.0.4
  lints: ^2.1.0

jaspr:
  uses-ssr: false
